apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecom-microservices-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ecom.example.com  # Replace with your actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecom-microservices-service
                port:
                  number: 80

