apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7  # You can specify a different version if needed
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"  # Change this password
            - name: MYSQL_DATABASE
              value: "ecommerce_db"
            - name: MYSQL_USER
              value: "ecommerce_user"
            - name: MYSQL_PASSWORD
              value: "ecommerce_password"
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None  # This allows the database to be accessed using the service name (mysql-service)



