apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecom-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/ecom"  # Change this path based on where you want the data stored
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecom-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
