apiVersion: v1
kind: Service
metadata:
  name: ecom-microservices-service
spec:
  selector:
    app: ecom-microservices
  ports:
    - protocol: TCP
      port: 80  # Expose service internally within the cluster
      targetPort: 8080  # Port your application is running on in the container
  type: ClusterIP  # Type of service, ClusterIP is for internal access
    # You can change this to NodePort or LoadBalancer if you need external access
